language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 7.1
    - php: hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    sed -i s/root/travis/ tests/config/common.php
    # sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
    # sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yii2_grid_utils;'
  - php yii_test migrate --interactive=0

script:
  - composer exec codecept run -vvv
